# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
Database:
  postgres:
    User:
      # If the user doesn't exist already, it is created
      Username: 'postgres'
      Password: 'postgres'
